branches:
  except:
    - /^bitbucket\/.*/
    - /^travis\/.*/
language: node_js
cache:
  directories:
    - "node_modules"
os:
  - linux
# Windows is not supported at all. Bummer.
# Testing on OS X makes no sense, when everything is tested on linux and in browsers
jobs:
  include:
    # stage test
    - node_js: '8' # npm test
    - node_js: '10' # npm test
    - node_js: '12' # npm test
    - node_js: '14' # npm test
    - node_js: '10'
      script: npm run wd
    # stage tag
    - stage: tag
      node_js: '10'
      install: skip
      script:
        - npm run legalReport
        - scripts/travisGithubTag.sh
