language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - '6'
  - '8'
  - '10'
os:
  - linux
# Windows is not supported at all. Bummer.
# Testing on OS X makes no sense, when everything is tested on linux and in browsers
matrix:
  include:
    - node_js: '8'
      script:
        - npm run wd
