language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - '6'
  - '8'
  - '10'
os:
  - linux
# Windows is not supported at all. Bummer.
# Testing on OS X makes no sense, when everything is tested on linux and in browsers
matrix:
  include:
    - node_js: '8'
      script:
        - npm run wd
jobs:
  include:
    - stage: tag
      node_js: '8'
      install: skip
      script:
        - echo TAG STAGE
    - stage: publish
      node_js: '8'
      script:
        - echo PUBLISH STAGE
stages:
  - test
  - tag
  - name: publish
    if: tag = version/**
