@startuml

class Function {
  +name: String <<readonly>>
  +/displayName: String
  +apply(…): Function
  +call(…): Function
  +bind(…): Function
  +toString(): String
}
class Error {
  +name: Any
  +message: Any
  +/stack: String <<readonly>>
  +toString(): String
}

interface FunctionWithImplementation

Function <.. FunctionWithImplementation: instanceof
FunctionWithImplementation --> "implementation" Function

abstract class Contract {
  +{static} displayNamePrefix: String
  +pre: Array <<readonly>>
  +post: Array <<readonly>>
  +exception: Array <<readonly>>
  +location: String <<readonly>>
  +{static} contractFunctionDisplayName(f: FunctionWithImplementation): String
  +{static} defineContractFunctionDisplayName(f: FunctionWithImplementation): void
  +{static} Contract(pre: Function[]?, post: Function[]?, exception: Function[]?)
  +{static} isAContractFunction(f: Any): Boolean
  +{static} dummyImplementation(): ContractFunction
}

class ImplementableContract {
  +{static} ImplementableContract(pre: Function[]?, post: Function[]?, exception: Function[]?)
  +implementation(implFunction: Function): ContractFunction
}
Contract <|-- ImplementableContract

interface ContractFunction {
  +location: String <<readonly>>
  +/displayName: String
  +bind(…): ContractFunction
}

Contract +-- ContractFunction
FunctionWithImplementation <|-- ContractFunction

ContractFunction --> "contract" Contract

abstract class ConditionError {
  +name: String = "Contract Condition Error"
  +self: Object <<readonly>>
  +args: ArrayLike <<readonly>>
  +message: String <<readonly>>
  +/stack: String <<multiline>>
  +{static} ConditionError(contractFunction, condition, self, args)
  #stackAddition(): String
  +{static} createMessage(contractFunction, condition, self, args): String
}
Error <|-- ConditionError

class ConditionMetaError {
  +{static} name: String <<readonly>>
  +error: Any <<readonly>>
  +message: String <<readonly>>
  +{static} ConditionMetaError(contractFunction, condition, self, args, error)
  #stackAddition(): String
  +{static} createMessage(contractFunction, condition, self, args): String
}

abstract class ConditionViolation {
  +{static} name: String <<readonly>>
  +message: String <<readonly>>
  +{static} ConditionViolation(contractFunction, condition, self, args)
  +{static} createMessage(contractFunction, condition, self, args): String
  +{static} verify(contractFunction, condition, self, args): void <<prototype>>
  +{static} verifyAll(contractFunction, conditions, self, args): void <<prototype>>
}
class PreconditionViolation {
  +{static} name: String <<readonly>>
  +message: String <<readonly>>
  +{static} PreconditionViolation(contractFunction, condition, self, args)
  +{static} createMessage(contractFunction, condition, self, args): String
}
class PostconditionViolation <<todo>> {
  +{static} name: String <<readonly>>
  +result: Any <<readonly>>
  +message: String <<readonly>>
  +{static} PostconditionViolation(contractFunction, condition, self, args, result: Any)
  #stackAddition(): String
  +{static} createMessage(contractFunction, condition, self, args): String
}

class ExceptionConditionViolation <<todo>> {
  +{static} name: String <<readonly>>
  +exception: Any <<readonly>>
  +message: String <<readonly>>
  +{static} ExceptionConditionViolation(contractFunction, condition, self, args, exception: Any)
  #stackAddition(): String
  +{static} createMessage(contractFunction, condition, self, args): String
}

ConditionError --> "contractFunction <<readonly>>" ContractFunction
ConditionError --> "condition <<readonly>>" Function
ConditionError --> "_stackSource <<readonly, frozen>>" Error

ConditionError <|-- ConditionMetaError
ConditionError <|-- ConditionViolation

ConditionViolation <|-- PreconditionViolation
ConditionViolation <|-- PostconditionViolation
ConditionViolation <|-- ExceptionConditionViolation

ImplementableContract ..> ConditionMetaError: <<use>>
ImplementableContract ..> PreconditionViolation: <<use>>
ImplementableContract ..> PostconditionViolation: <<use>>
ImplementableContract ..> ExceptionConditionViolation: <<use>>
ImplementableContract ..> ContractFunction: <<generates>>

@enduml
